### ISSUE TITLE
When I deploy this example project, the setup wizard is started and this should not be

### ISSUE THREAD

**Issue by vishal-reddy** [wedeploy/boilerplate-liferay-dxp#23]

**Comment by albertininm** [comment]
Hi @vishal-reddy. I was not able to reproduce this issue.
I deployed the example exactly how it is and after that I deployed it chaging the property `setup.wizard.enabled` to be `true`.
The first attept didn't show the setup wizard page in my first access. The second one opened this:
![screen shot 2018-10-24 at 1 33 38 pm](https://user-images.githubusercontent.com/19316913/47446361-72bcb680-d791-11e8-8731-b8ac72639294.png)

Could you please share the steps to reproduce the behavior that you reported?

**Comment by vishal-reddy** [comment]
okay. I will just try again today and get back to you with my steps.

**Comment by albertininm** [comment]
Hi @vishal-reddy , did you have time to check if it's still reproducible?

**Comment by albertininm** [comment]
Hi @vishal-reddy , we are going to close this issue due to inactivity.
If you are still facing this, feel free to contact me.
